### ISSUE TITLE
Error after generating new build.js with browserify

### ISSUE THREAD

**Issue by sballieu** [linkedconnections/client.js#11]
After generating a new build.js file (using the browserify command from the README file), I get following error when executing the example in the dist folder:

![error2](https://cloud.githubusercontent.com/assets/9060936/14409410/d8c734dc-ff12-11e5-919e-ea7997c689b4.png)

**Comment by pietercolpaert** [comment]
Without having investigated too much, is this problem firefox-specific? Does this problem happen in chrome?

It looks like this is not working: https://github.com/linkedconnections/client.js/blob/master/lib/http/HttpFetcher.js#L85

**Comment by sballieu** [comment]
No, this is the error on Chrome:
![error3](https://cloud.githubusercontent.com/assets/9060936/14457587/c3b988de-00ab-11e6-885e-1ca9409132dd.png)

Chrome refers to the same line as to where you think the error is located.

**Comment by pietercolpaert** [comment]
It works for me... I have put my latest version over here:

http://demo.linkedconnections.org/dist/example/

Can you check whether that works and try to find out what isn't working for you?

**Comment by sballieu** [comment]
This works for me.

Did you generate a new build.js file with browserify? The build.js file in this repo also works for me but when I generate a new one, I get this error.

I use the following command from the README to generate a build.js

``` bash
browserify lib/lc-client.js -d -p [minifyify --no-map] > dist/build.js
```

This is the resulting file:
[build.js.zip](https://github.com/linkedconnections/client.js/files/214985/build.js.zip)

**Comment by sballieu** [comment]
The code fails because `self._active[requestId].request.xhr` is undefined.

**Comment by pietercolpaert** [comment]
yes, I did rebuild build.js with the browserify command. Check for yourself:
`curl http://demo.linkedconnections.org/dist/build.js | grep request.xhr`

**Comment by sballieu** [comment]
Can you confirm that this is not working:
http://users.ugent.be/~sballieu/test/example/index.html

This is with my rebuilded build.js file.

**Comment by pietercolpaert** [comment]
It's indeed not working. Do you work on the current master branch and did you change anything? Can you check your version of browserify? I think that's the problem here... The undocumented xhr object [1](yes, it's quite a hack) I rely upon can be found in the latest version of http-browserify [2], which is the component within browserify which translates all the http requests within nodejs to XHR object for browsers.

[1] https://github.com/substack/http-browserify/blob/master/lib/request.js#L9
[2] https://github.com/substack/http-browserify

I'm not sure whether this is used within browserify right now, but there also exists a different repository: https://github.com/thenativeweb/http-browserify-2/.

My hypothesis is that you use an older version of browserify which uses an old version of http-browserify, or you use a newer version of browserify that uses https://github.com/thenativeweb/http-browserify-2/  (I'm not sure whether browserify ended up adopting this).

**Comment by pietercolpaert** [comment]
As a reference: I'm using browserify 8.1.1

```
browserify --version
```

**Comment by sballieu** [comment]
I'm using the latest version: 13.0.0

**Comment by pietercolpaert** [comment]
Wow, seems like I'm lacking behind a bit! ^^

Now browserify appears to be using this HTTP conversion: https://www.npmjs.com/package/stream-http

I'll try to fix it after the coffee break here!

**Comment by pietercolpaert** [comment]
@sballieu I have fixed it and published a new version of the code to npm. Can you test this?

**Comment by sballieu** [comment]
It works in Chrome but I get an error for the strem.close. In Firefox there is an error for: request._fetchResponse

Chrome:
![error1](https://cloud.githubusercontent.com/assets/9060936/14472212/66956cd0-00f2-11e6-9e57-ff38025a14d2.png)

Firefox:
![error2](https://cloud.githubusercontent.com/assets/9060936/14472213/66977048-00f2-11e6-97b0-2a66efdd7899.png)

**Comment by pietercolpaert** [comment]
I cannot reproduce the stream.close() problem. It does not occur here: http://demo.linkedconnections.org/dist/example/. Does this version give problems on your machine?

I did reproduce the firefox problem with fetchResponse though. Annoying situation there, also see https://github.com/jhiesey/stream-http/issues/39

**Comment by sballieu** [comment]
Yes, your version gives exactly the same error.

**Comment by pietercolpaert** [comment]
Can you check now @sballieu? :)

**Comment by sballieu** [comment]
It works :smiley:

**Comment by pietercolpaert** [comment]
At last! :dancer:
